### ISSUE TITLE
Enable several different configurations

### ISSUE THREAD

**Issue by arokem** [learning-2-learn/jhub-deployment#37]
Sometimes we need an army of relatively small machines, but for some things (e.g., running ICA on large recordings), we need one big machine (possibly, with its attendant army of small machines). Currently, we use a tljh instance for that, but it would be a lot cleaner to use a separate configuration of this hub to allow this. This is implemented in https://github.com/neurohackademy/nh2020-jupyterhub/, so we should be able to port it here as well.

**Comment by consideRatio** [comment]
This is setup with small, medium, large instances, and now they all work.
