### ISSUE TITLE
Updgrade dask.distributed to a version that has PipInstall plugin

### ISSUE THREAD

**Issue by arokem** [learning-2-learn/jhub-deployment#71]
https://distributed.dask.org/en/latest/plugins.html#distributed.diagnostics.plugin.PipInstall

**Comment by consideRatio** [comment]
I think upgrading the base image to `2021.02.19` may do the trick! Some traces of me deducing that are below, where I also avoid the absolute latest base image as it contain jupyterlab 3 which we have incompatible extensions with.

https://hub.docker.com/r/pangeo/pangeo-notebook/tags?page=1&ordering=last_updated

https://github.com/conda-forge/pangeo-notebook-feedstock/blame/4a09e2ebe5f26fcc281d3049dce37205cd5bdbca/recipe/meta.yaml#L13

https://github.com/conda-forge/pangeo-dask-feedstock/blame/c4f842372ef2c45febd7c8f5e6ec4bc13c7be8a1/recipe/meta.yaml#L13-L14
