### ISSUE TITLE
Memory allocated seems double than requested

### ISSUE THREAD

**Issue by arokem** [learning-2-learn/jhub-deployment#76]
When starting an instance with 6 GB, the notebook indicator says 12 GB are available, with 24 GB, we get 48GB in the notebook indicator. This might be an issue with the indicator, or it might be that we get too much memory.

**Comment by consideRatio** [comment]
Ah this is because I have made it limited to the double while the requested/guaranteed memory is half. Perhaps an action point would be to clarify that in the choice of profile before starting the server to avoid confusion, rather than not allowing for some additional memory usage if available?

**Comment by arokem** [comment]
Yes - I think that a small explanation on the front page ("max: XX GB, guaranteed: YY GB") would be sufficient
