### ISSUE TITLE
Okay to upgrade to bycycle from 0.1.* to 1.0.0?

### ISSUE THREAD

**Issue by consideRatio** [learning-2-learn/jhub-deployment#90]
I'm debugging a failure to build the image after bumping #89, and one thing I just look for by default is for any pinned package that may be outdated. Often what happens is outdated package pinnings in turn require outdated packages which in turn may be incompatible. Due to that, I like staying updated with everything installed to avoid such issues ahead of time.

I'm not sure what made the build fail yet, but I figure I'd ask if you are okay with bumping bycycle from 0.1.* to 1.0.0.

The changelog for the bycycle package is here: https://bycycle-tools.github.io/bycycle/changelog.html

**Comment by arokem** [comment]
Yeah - we haven't been using it much recently, so I don't think this will
hurt anything.
